import { Button, VerticalBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    title: "HEJ TEIS";
    min-width: 200px;
    min-height: 200px;
    in-out property<int> counter: 42;
    callback request-increase-value();
    VerticalBox { 
        Text {
            text: "Counter: \{root.counter}";
        }
        Button {
            text: "Increase value";
            clicked => { 
                root.request-increase-value();
            }
        }
     }
}
