import { Button, VerticalBox, HorizontalBox, ProgressIndicator, GridBox, TextEdit } from "std-widgets.slint";
export global globalVariables {
    in-out property <int> activePage: 0;
    in-out property <float> count: 0;
    in-out property <bool> paused: true;
    in-out property <string> songName: "SANG";
    in-out property <string> username;
}

export component Divider {
    Rectangle {
        background: #3b3a3a;
        height: 5px;
    }
}

export component HomeBtn {
    Button {
        icon: @image-url(".././assets/home.png");
        text: "Home";
        clicked() => {
            globalVariables.activePage = 2;
        }
    }
}

export component ProfileBtn {
    Button {
        icon: @image-url(".././assets/profile.png");
        text: "Profile";
        clicked() => {
            globalVariables.activePage = 3;
        }
    }
}

export component LibraryBtn {
    Button {
        icon: @image-url(".././assets/library.png");
        text: "Library";
        clicked() => {
            globalVariables.activePage = 5;
        }
    }
}

export component RecentPlaylistBtn {
    Button {
        text: "%{recent playlist}%";
    }
}

export component Interface {
    @children
    timer := Timer {
        interval: 1ms;
        running: false;
        triggered() => {
            if globalVariables.count >= 10 {
                self.running = false;
            }
            globalVariables.count = globalVariables.count + 0.01;
            debug(globalVariables.count);
        }
    }

    GridLayout {
        Rectangle {
            background: #121212;
            width: 150px;
            VerticalBox {
                padding: 25px;
                alignment: space-around;
                HomeBtn { }

                Divider { }

                ProfileBtn { }

                Divider { }

                LibraryBtn { }

                Divider { }

                RecentPlaylistBtn { }
            }
        }

        Rectangle {
            HorizontalBox {
                padding-top: 30px;
                alignment: center;
                Text {
                    text: "Now playing: " + globalVariables.songName;
                    font-size: 24px;
                }

                Button {
                    height: parent.height / 2;
                    icon: @image-url(".././assets/l.png");
                }

                Button {
                    height: parent.height / 2;
                    icon: globalVariables.paused ? @image-url(".././assets/play.png") : @image-url(".././assets/pause.png");
                    clicked() => {
                        globalVariables.paused = !globalVariables.paused;
                        timer.running = !globalVariables.paused;
                    }
                }

                Button {
                    height: parent.height / 2;
                    icon: @image-url(".././assets/r.png");
                }
            }

            VerticalBox {
                alignment: start;
                padding-bottom: 100px;
                ProgressIndicator {
                    padding-top: 100px;
                    height: 10px;
                    progress: globalVariables.count / 10;
                }
            }

            background: #b5832e;
            height: 80px;
            colspan: 2;
            row: 1;
        }
    }
}

export component PlaylistBtn inherits Rectangle {
    in-out property text <=> txt.text;
    callback clicked <=> touch.clicked;
    border-radius: 10px;
    background: touch.pressed ? #b5832e : touch.has-hover ? #b5842ea2 : #b5832e;
    txt := Text {
        x: (parent.width - self.width) / 2 + (touch.pressed ? 2px : 0);
        y: (parent.height - self.height) / 2 + (touch.pressed ? 1px : 0);
        color: touch.pressed ? #fff : #eee;
    }

    touch := TouchArea { }
}

export global callbacks {
    callback register(string, string, string);
    callback login(string, string);
    callback logout();
    callback getUserInfo();
}
