import { Button, VerticalBox, HorizontalBox, ProgressIndicator, GridBox, LineEdit, TextEdit } from "std-widgets.slint";
import { globalVariables, Divider, HomeBtn, ProfileBtn, LibraryBtn, CreatePlaylist, Interface, PlaylistBtn, callbacks } from "common.slint";

export component Home inherits Window {
    GridLayout {
        Row {
            Interface {
                GridLayout {
                    padding-left: 150px;
                    padding-bottom: 80px;
                    HorizontalBox {
                        GridBox {
                            Rectangle {
                                HorizontalBox {
                                    alignment: start;
                                    Image {
                                        width: 25px;
                                        source: @image-url(".././assets/search.png");
                                    }
                                }

                                LineEdit {
                                    placeholder-text: "Search...";
                                    width: parent.width - 75px;
                                    key-pressed(event) => {
                                        debug(event.text + " ");
                                        return EventResult.accept;
                                    }
                                }

                                height: 50px;
                            }

                            Rectangle {
                                GridBox {
                                    HorizontalBox {
                                        alignment: center;
                                        Rectangle {
                                            VerticalBox {
                                                Text {
                                                    text: "WELCOME BACK!";
                                                    font-size: 30px;
                                                    color: white;
                                                    vertical-alignment: top;
                                                    horizontal-alignment: center;
                                                }

                                                Text {
                                                    text: "What do you want to listen to today?";
                                                    font-size: 20px;
                                                    color: white;
                                                    horizontal-alignment: center;
                                                }
                                            }
                                        }

                                        colspan: 3;
                                    }

                                    PlaylistBtn {
                                        Text {
                                            text: "DAILY MIX #1";
                                            font-size: 20px;
                                            color: white;
                                        }

                                        row: 1;
                                    }

                                    PlaylistBtn {
                                        Text {
                                            text: "DAILY MIX #2";
                                            font-size: 20px;
                                            color: white;
                                        }
                                    }

                                    PlaylistBtn {
                                        Text {
                                            text: "DAILY MIX #3";
                                            font-size: 20px;
                                            color: white;
                                        }
                                    }
                                }

                                row: 1;
                                col: 0;
                                background: Colors.rgba(255, 255, 255, 0.2);
                                border-radius: 10px;
                            }
                        }
                    }
                }
            }
        }
    }
}
