import { Button, VerticalBox, HorizontalBox, ProgressIndicator, GridBox } from "std-widgets.slint";
import { globalVariables, Divider, HomeBtn, ProfileBtn, LibraryBtn, RecentPlaylistBtn, Interface } from "common.slint";

export component Home inherits Window {
    GridLayout {
        Row {
            Interface {
                GridLayout {
                    padding-left: 150px;
                    padding-bottom: 80px;
                    Rectangle {
                        GridBox {
                            Row {
                                Text {
                                    text: "HOME";
                                    font-size: 24px;
                                }
                            }
                        }

                        border-width: 10px;
                        border-color: Colors.red;
                    }
                }
            }
        }
    }
}
