import { Button, VerticalBox, HorizontalBox, ProgressIndicator, GridBox, LineEdit, TextEdit } from "std-widgets.slint";
import { globalVariables, Divider, HomeBtn, ProfileBtn, LibraryBtn, CreatePlaylist, Interface, PlaylistBtn } from "common.slint";

export component Library inherits Window {
    GridLayout {
        Row {
            Interface {
                GridLayout {
                    padding-left: 150px;
                    padding-bottom: 80px;
                    HorizontalBox {
                        GridBox {
                            Rectangle {
                                HorizontalBox {
                                    alignment: start;
                                    Image {
                                        width: 25px;
                                        source: @image-url(".././assets/search.png");
                                    }
                                }

                                LineEdit {
                                    placeholder-text: "Search...";
                                    width: parent.width - 75px;
                                }

                                height: 50px;
                            }

                            Rectangle {
                                GridBox {
                                    PlaylistBtn {
                                        Text {
                                            text: "playlist1";
                                            font-size: 20px;
                                            color: white;
                                        }

                                        clicked() => {
                                            globalVariables.activePage = 4;
                                        }
                                    }

                                    PlaylistBtn {
                                        Text {
                                            text: "playlist2";
                                            font-size: 20px;
                                            color: white;
                                        }
                                    }

                                    PlaylistBtn {
                                        Text {
                                            text: "playlist3";
                                            font-size: 20px;
                                            color: white;
                                        }
                                    }

                                    PlaylistBtn {
                                        Text {
                                            text: "playlist4";
                                            font-size: 20px;
                                            color: white;
                                        }

                                        row: 1;
                                    }

                                    PlaylistBtn {
                                        Text {
                                            text: "playlist5";
                                            font-size: 20px;
                                            color: white;
                                        }
                                    }

                                    PlaylistBtn {
                                        Text {
                                            text: "playlist6";
                                            font-size: 20px;
                                            color: white;
                                        }
                                    }
                                }

                                row: 1;
                                col: 0;
                                background: Colors.rgba(255, 255, 255, 0.2);
                                border-radius: 10px;
                            }
                        }
                    }
                }
            }
        }
    }
}
