import { Button, VerticalBox, HorizontalBox, LineEdit } from "std-widgets.slint";
import { globalVariables, callbacks } from "common.slint";

export component Login inherits Window {
    property <string> email;
    property <string> password;
    VerticalBox {
        alignment: center;
        HorizontalBox {
            alignment: center;
            Rectangle {
                background: #b5832e;
                width: 250px;
                height: 400px;
                border-radius: 25px;
                Text {
                    text: "Login";
                    font-size: 30px;
                    color: white;
                    horizontal-alignment: center;
                    vertical-alignment: center;
                    y: 35px;
                }

                emailInput := LineEdit {
                    placeholder-text: "Email";
                    text: root.email;
                    width: 200px;
                    x: 25px;
                    y: 100px;
                }

                passwordInput := LineEdit {
                    placeholder-text: "Password";
                    text: root.password;
                    input-type: InputType.password;
                    width: 200px;
                    x: 25px;
                    y: 150px;
                }

                Rectangle {
                    width: 200px;
                    x: 25px;
                    y: 80px;
                    Text {
                        text: "Don't have an account? Click here!";
                    }

                    TouchArea {
                        width: 150px;
                        height: 25px;
                        clicked => {
                            globalVariables.activePage = 0;
                        }
                    }
                }

                Button {
                    text: "Login";
                    x: 97px;
                    y: 350px;
                    clicked => {
                        callbacks.login(emailInput.text, passwordInput.text);
                    }
                }
            }
        }
    }
}
