import { Page } from "common.slint";
import { Register } from "register.slint";
import { Login } from "login.slint";
import { Home } from "home.slint";
import { Profile } from "profile.slint";

export component MainWindow inherits Window {
    title: "PhamiJam";
    min-width: 1024px;
    min-height: 576px;
    default-font-family: "Lexend";
    icon: @image-url(".././assets/P-modified.png");
    background: #dba43a;
    main := HorizontalLayout {
        if Page.activePage == 0: Register {
            visible: true;
        }
        if Page.activePage == 1: Login {
            visible: true;
        }
        if Page.activePage == 2:  Home {
            visible: true;
        }
        if Page.activePage == 3:  Profile {
            visible: true;
        }
    }
}
