import { globalVariables, callbacks } from "common.slint";
import { Register } from "register.slint";
import { Login } from "login.slint";
import { Home } from "home.slint";
import { Profile } from "profile.slint";
import { Playlist } from "playlist.slint";
import { VerticalBox, Button } from "std-widgets.slint";

export component MainWindow inherits Window {
    in-out property <int> globalActivePage <=> globalVariables.activePage;
    in-out property <bool> showToast;
    in-out property <string> toastMessage;
    in-out property <color> toastColor;
    in-out property <string> globalUsername <=> globalVariables.username;
    callback register <=> callbacks.register;
    callback login <=> callbacks.login;
    callback logout <=> callbacks.logout;
    callback getUserInfo <=> callbacks.getUserInfo;
    title: "PhamiJam";
    min-width: 1024px;
    min-height: 576px;
    default-font-family: "Lexend";
    icon: @image-url(".././assets/P-modified.png");
    background: #dba43a;
    main := HorizontalLayout {
        if globalVariables.activePage == 0: Register {
            visible: true;
        }
        if globalVariables.activePage == 1: Login {
            visible: true;
        }
        if globalVariables.activePage == 2: Home {
            visible: true;
        }
        if globalVariables.activePage == 3:  Profile {
            visible: true;
        }
        if globalVariables.activePage == 4:  Playlist {
            visible: true;
        }
    }

    Rectangle {
        opacity: root.showToast ? 1.0 : 0.0;
        animate opacity { duration: 250ms; }
        background: root.toastColor;
        border-radius: 8px;
        padding: 8px;
        y: parent.height - 60px;
        x: (parent.width - self.width) / 2;
        width: 300px;
        height: 40px;
        Text {
            text: root.toastMessage;
            color: white;
            horizontal-alignment: center;
            vertical-alignment: center;
        }
    }
}
