import { Button, VerticalBox, HorizontalBox, ProgressIndicator, GridBox } from "std-widgets.slint";
import { globalVariables, Divider, HomeBtn, ProfileBtn, LibraryBtn, RecentPlaylistBtn, Interface, callbacks } from "common.slint";

export component Profile inherits Window {
    property <string> username: globalVariables.username;
    init => {
        callbacks.getUserInfo();
    }
    GridLayout {
        Row {
            Interface {
                GridLayout {
                    padding-left: 150px;
                    padding-bottom: 80px;
                    Rectangle {
                        GridBox {
                            GridLayout {
                                Rectangle {
                                    Image {
                                        width: 250px;
                                        height: 250px;
                                        source: @image-url(".././assets/catPHOENIX.jpg");
                                    }

                                    background: yellow;
                                }

                                Rectangle {
                                    Text {
                                        text: username;
                                        font-size: 24px;
                                    }
                                }

                                Button {
                                    text: "Logout";
                                    clicked => {
                                        callbacks.logout();
                                    }
                                }
                            }
                        }

                        border-width: 10px;
                        border-color: Colors.red;
                    }
                }
            }
        }
    }
}
