import { Button, VerticalBox, HorizontalBox, LineEdit } from "std-widgets.slint";
import {globalVariables} from "common.slint";

export component Register inherits Window {
    background: #dba43a;
    VerticalBox {
        alignment: center;
        HorizontalBox {
            alignment: center;
            Rectangle {
                background: #b5832e;
                width: 250px;
                height: 400px;
                border-radius: 25px;
                LineEdit {
                    placeholder-text: "Username";
                    width: 200px;
                    x: 25px;
                    y: 100px;
                }

                LineEdit {
                    placeholder-text: "Password";
                    input-type: password;
                    width: 200px;
                    x: 25px;
                    y: 150px;
                }

                LineEdit {
                    placeholder-text: "Email";
                    width: 200px;
                    x: 25px;
                    y: 200px;
                }

                Rectangle {
                    width: 200px;
                    x: 25px;
                    y: 80px;
                    Text {
                        text: "Have an account? Click here!";
                    }

                    TouchArea {
                        width: 150px;
                        height: 25px;
                        clicked => {
                            globalVariables.activePage = 1;
                        }
                    }
                }

                Button {
                    text: "Login";
                    x: 97px;
                    y: 350px;
                    clicked => {
                        globalVariables.activePage = 2;
                    }
                }
            }
        }
    }
}
