import { Button, VerticalBox, HorizontalBox, LineEdit } from "std-widgets.slint";
import {globalVariables, callbacks} from "common.slint";

export component Register inherits Window {
    property <string> username;
    property <string> email;
    property <string> password;
    in-out property <string> status;
    callback popup();
    background: #dba43a;
    VerticalBox {
        alignment: center;
        HorizontalBox {
            alignment: center;
            Rectangle {
                background: #b5832e;
                width: 250px;
                height: 400px;
                border-radius: 25px;
                usernameInput := LineEdit {
                    placeholder-text: "Username";
                    text: root.username;
                    width: 200px;
                    x: 25px;
                    y: 100px;
                }

                passwordInput := LineEdit {
                    placeholder-text: "Password";
                    text: root.password;
                    input-type: InputType.password;
                    width: 200px;
                    x: 25px;
                    y: 150px;
                }

                emailInput := LineEdit {
                    placeholder-text: "Email";
                    text: root.email;
                    width: 200px;
                    x: 25px;
                    y: 200px;
                }

                Rectangle {
                    width: 200px;
                    x: 25px;
                    y: 80px;
                    Text {
                        text: "Have an account? Click here!";
                    }

                    TouchArea {
                        width: 150px;
                        height: 25px;
                        clicked => {
                            globalVariables.activePage = 1;
                        }
                    }
                }

                Button {
                    text: "Login";
                    x: 97px;
                    y: 350px;
                    clicked => {
                        debug("Login clicked");
                        callbacks.register(usernameInput.text, passwordInput.text, emailInput.text)
                    }
                }

                popup := PopupWindow {
                    Rectangle {
                        height: 100%;
                        width: 100%;
                        background: yellow;
                    }

                    x: 20px;
                    y: 20px;
                    height: 50px;
                    width: 50px;
                }

                Text {
                    text: status;
                    color: red;
                    x: 25px;
                    y: 300px;
                    font-size: 14px;
                    horizontal-alignment: left;
                    width: 200px;
                }
            }
        }
    }
}
