import { Button, VerticalBox, HorizontalBox } from "std-widgets.slint";

export component HomeScreen inherits Window {
    title: "PhamiJam";
    min-width: 1024px;
    min-height: 576px;
    icon: @image-url(".././assets/P-modified.png");
    background: #dba43a;
    GridLayout {
        Row {
            Rectangle {
                background: #121212;
                width: 150px;
            }

            Rectangle {
                background: #b5832e;
                height: 80px;
                row: 1;
            }

            Rectangle {
                background: #b5832e;
                height: 80px;
                col: 1;
                row: 1;
            }
        }
    }
}
