import { Button, VerticalBox, HorizontalBox, LineEdit } from "std-widgets.slint";
import { HomeScreen } from "home_screen.slint";
import { test } from "common.slint";

export component RegisterScreen inherits Window {
    title: "PhamiJam";
    min-width: 1024px;
    min-height: 576px;
    icon: @image-url(".././assets/P-modified.png");
    background: #dba43a;
    main := HorizontalLayout {
        if test.activepage == 1: HomeScreen {
            visible: true;
        }
    }

    VerticalBox {
        alignment: center;
        HorizontalBox {
            alignment: center;
            Rectangle {
                background: #b5832e;
                width: 250px;
                height: 400px;
                border-radius: 25px;
                LineEdit {
                    placeholder-text: "Username";
                    width: 200px;
                    x: 25px;
                    y: 50px;
                }

                LineEdit {
                    placeholder-text: "Password";
                    input-type: password;
                    width: 200px;
                    x: 25px;
                    y: 150px;
                }

                LineEdit {
                    placeholder-text: "Email";
                    width: 200px;
                    x: 25px;
                    y: 200px;
                }

                Button {
                    text: "Login";
                    x: 97px;
                    y: 350px;
                    clicked => {
                        test.activepage = 1;
                    }
                }
            }
        }
    }
}
